//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace прокат.авто.База_Данных
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AvtoProkatEntities2 : DbContext
    {
        public AvtoProkatEntities2()
            : base("name=AvtoProkatEntities2")
        {
        }
        private static AvtoProkatEntities2 _Context;
            public static AvtoProkatEntities2 GetContext()
        {
            if (_Context == null)
                _Context = new AvtoProkatEntities2();
            return _Context;
        }
       
    

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Автомобили> Автомобили { get; set; }
        public virtual DbSet<АрендованныеАвто> АрендованныеАвто { get; set; }
        public virtual DbSet<ВходПользователи> ВходПользователи { get; set; }
        public virtual DbSet<Клиенты> Клиенты { get; set; }
        public virtual DbSet<МаркиАвтомобиля> МаркиАвтомобиля { get; set; }
        public virtual DbSet<СистемаШтрафов> СистемаШтрафов { get; set; }
        public virtual DbSet<Скидка> Скидка { get; set; }
        public virtual DbSet<ТипАвтомобиля> ТипАвтомобиля { get; set; }
        public virtual DbSet<ТипКПП> ТипКПП { get; set; }
        public virtual DbSet<Штрафы> Штрафы { get; set; }
    }
}
