//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace прокат.авто.База_Данных
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Автомобили
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Автомобили()
        {
            this.АрендованныеАвто = new HashSet<АрендованныеАвто>();
        }
       
        public string GetPhoto
        {
            get
            {
                if (ФотоАвтомобиля is null)
                    return null;
                return Directory.GetCurrentDirectory() + @"\Images\" + ФотоАвтомобиля.Trim();
            }
        }

        public int КодАвтомобиля { get; set; }
        public int КодТарифа { get; set; }
        public int КодМарки { get; set; }
        public string Модель { get; set; }
        public int КодКПП { get; set; }
        public string ГодВыпуска { get; set; }
        public string Госномер { get; set; }
        public double СтоимостьАрендыВМинуту { get; set; }
        public double СтоимостьАрендыВЧас { get; set; }
        public double СтоимостьАрендыВСутки { get; set; }
        public string ФотоАвтомобиля { get; set; }
        public bool Статус { get; set; }
    
        public virtual МаркиАвтомобиля МаркиАвтомобиля { get; set; }
        public virtual ТипАвтомобиля ТипАвтомобиля { get; set; }
        public virtual ТипКПП ТипКПП { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<АрендованныеАвто> АрендованныеАвто { get; set; }
    }
}
