//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace прокат.авто.База_Данных
{
    using System;
    using System.Collections.Generic;
    
    public partial class АрендованныеАвто
    {
        public int КодАренды { get; set; }
        public int КодКлиента { get; set; }
        public int КодАвтомобиля { get; set; }
        public System.DateTime Дата_Время_Выдачи { get; set; }
        public System.DateTime Дата_Время_Возврата { get; set; }
        public double СуммаЗаАренду { get; set; }
        public Nullable<int> КодСкидки { get; set; }
        public Nullable<int> КодНарушения { get; set; }
        public int ИтоговаяСумма { get; set; }
    
        public virtual Автомобили Автомобили { get; set; }
        public virtual Клиенты Клиенты { get; set; }
        public virtual Скидка Скидка { get; set; }
        public virtual Штрафы Штрафы { get; set; }
    }
}
