//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace прокат.авто.База_Данных
{
    using System;
    using System.Collections.Generic;
    
    public partial class Скидка
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Скидка()
        {
            this.АрендованныеАвто = new HashSet<АрендованныеАвто>();
        }
    
        public int КодСкидки { get; set; }
        public string НаименованиеСкидки { get; set; }
        public double Процент { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<АрендованныеАвто> АрендованныеАвто { get; set; }
    }
}
