//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace прокат.авто.База_Данных
{
    using System;
    using System.Collections.Generic;
    
    public partial class Штрафы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Штрафы()
        {
            this.АрендованныеАвто = new HashSet<АрендованныеАвто>();
        }
    
        public int КодНарушения { get; set; }
        public int КодАренды { get; set; }
        public int КодШтрафа { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<АрендованныеАвто> АрендованныеАвто { get; set; }
        public virtual СистемаШтрафов СистемаШтрафов { get; set; }
    }
}
